package ${package}.kny;

/**
 * Generated by the KnY Tweaks MCreator plugin.
 *
 * This scaffold intentionally keeps registration timing visible until Kimetsunoyaiba Tweaks
 * exposes a compact registerSword adapter that does not require template access to the owning
 * mod event bus and DeferredRegister.
 */
public final class ${name}KnyNichirinSword {
    private ${name}KnyNichirinSword() {}

    public static void register(net.minecraftforge.registries.DeferredRegister<net.minecraft.world.item.Item> items) {
        com.lerdorf.kimetsunoyaibamultiplayer.api.KnYAPI.createSword("${data.registryName}")
            .breathingStyle("${data.breathingStyle}", null)
            .styleRange(${data.styleRange})
            .category(com.lerdorf.kimetsunoyaibamultiplayer.api.SwordRegistry.SwordCategory.${data.category})
            .swordLevel(${data.swordLevel})
            .durability(${data.durability})
            .build(items);
    }
}
